
version: '2.0'

volumes:
    db:
    data_dir:

services:
    app:
        build: .
        restart: always
        depends_on:
            - db
            - redis
        environment:
            EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_URL: postgres://mygpo:mygpo@db/mygpo
            CELERY_BROKER_URL: "redis://redis:6379//"
            # Debug must be true when using development server
            DEBUG: ${DEBUG}
        volumes:
            - "data_dir:/usr/src/mygpo"
        ports:
            - "8000:8000"
        networks:
            - default
            - caddy

    db:
        image: "postgres:alpine"
        restart: always
        volumes:
            - "db:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: mygpo
            POSTGRES_PASSWORD: mygpo
        restart: always
        expose: 
            - "5432"

    redis:
        image: "redis:alpine"

    beat:
        image: gpodder_app
        restart: always
        environment:
            EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_URL: postgres://mygpo:mygpo@db/mygpo
            LOGGING_CELERY_LEVEL: INFO
        volumes_from:
            - app
        entrypoint:
            - celery
            - -A
            - mygpo
            - beat
            - -b
            - "redis://redis:6379//"
            - "--scheduler"
            - django_celery_beat.schedulers:DatabaseScheduler

    worker:
        image: gpodder_app
        restart: always
        environment:
            EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_URL: postgres://mygpo:mygpo@db/mygpo
            LOGGING_CELERY_LEVEL: INFO
        volumes_from:
            - app
        entrypoint:
            - celery
            - -A
            - mygpo
            - -b
            - "redis://redis:6379//"
            - worker

networks:
    caddy:
        external:
            name: caddy_default
